name: Deploy to GAE

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python 3.9
      uses: actions/setup-python@v2
      with:
      python-version: "3.9"
    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCLOUD_PROJECTID }}
          credentials: ${{ secrets.GCLOUD_APP_DEPLOYER_ACCOUNT }}